// app/layout.tsx
import { getStoreData } from '@/lib/getStore'
import { ThemeProvider } from './context'
import { Inter, Poppins, Open_Sans} from 'next/font/google';
import { Metadata } from 'next';
import QueryProvider from './queryProvider';
import Provider from './provider';

const inter = Poppins({ subsets: ["latin"], weight: '500' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, searchParams }: any) {


  return (
    <html className='' lang="pt-BR">
      <body className={`${inter.className} `}>

        
          {children}
        

      </body>
    </html>
  )
}
