import { getStoreData } from "@/lib/getStore"
import { ThemeProvider } from '@/app/context'
import '../../globals.css'
import Head from "next/head"
import Image from "next/image"
import CartCustom from "@/components/cart"
import { UserCircle } from "lucide-react"
import SheetCustom from "@/components/sheet"
import SearchDrawer from "@/components/searchDrawer"
import { CarouselDemo } from "@/components/carousel"
import Link from "next/link"
import { Poppins } from "next/font/google"
import { Metadata } from "next"
import Provider from "@/app/provider"
import QueryProvider from "@/app/queryProvider"

const inter = Poppins({ subsets: ["latin"], weight: '500' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function StoreLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { store: string }
}) {
  const store = await getStoreData('teste')
  if (store === null) {
    return (
      <html lang="pt-BR">
        <body>
          <div>Loja não encontrada</div>
        </body>
      </html>
    )
  }

  return (
    <html className="overflow-x-hidden w-screen" lang="pt-BR">
      <body className={`h-screen w-screen overflow-x-hidden  overflow-y-auto`}>
        <ThemeProvider theme={store.theme}>
          <Head>
            <link rel="preload" as="image" href={store.theme.logoUrl} />
          </Head>

          <Provider>
            <QueryProvider>
              {children}
            </QueryProvider>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
