import { getStoreData } from "@/lib/getStore"
import { ThemeProvider } from '@/app/context'
import Head from "next/head"
import '@/app/globals.css'
import Image from "next/image"
import CartCustom from "@/components/cart"
import { UserCircle } from "lucide-react"
import SheetCustom from "@/components/sheet"
import SearchDrawer from "@/components/searchDrawer"
import { CarouselDemo } from "@/components/carousel"
import Link from "next/link"
import { Poppins } from "next/font/google"
import { Metadata } from "next"
import Provider from "@/app/provider"
import QueryProvider from "@/app/queryProvider"
import AppThemeProvider from "@/components/context/theme"

const inter = Poppins({ subsets: ["latin"], weight: '500' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function StoreLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { store: string }
}) {
  const store = await getStoreData('teste')
  if(!store) {
    return <div className="w-screen h-screen flex justify-center items-center">
      <h1 className="text-2xl font-bold">Loja não encontrada</h1>
    </div>
  }


  const cssVariables = `
    :root {
      --primary: ${store?.theme.light.primaryColor};
      --secondary: ${store?.theme.light.secondaryColor};
    }
    .dark {
      --primary: ${store?.theme.dark.primaryColor};
      --secondary: ${store?.theme.dark.secondaryColor};
    }
  `;

  return (
    <div className="h-screen overflow-x-hidden  w-screen" lang="pt-BR">
      <style id="dynamic-theme">{cssVariables}</style>
      <Head>
        <link rel="preload" as="image" href={store.theme.logoUrlLight} />
      </Head>
      <div className={`h-screen ${inter.className} overflow-x-hidden n w-screen`}>
        <ThemeProvider theme={store!.theme}>
            <Provider>
              <QueryProvider>
                {children}
              </QueryProvider>
            </Provider>
        </ThemeProvider>
      </div>
    </div>
  )
}

/*return (
  <html className="h-screen overflow-x-hidden  w-screen" lang="pt-BR">
    <head>
      <link rel="preload" as="image" href={store.theme.logoUrl} />
      <style color={store.theme.light.primaryColor}></style>
    </head>
    <body className={`h-screen ${inter.className} overflow-x-hidden n w-screen`}>
      <ThemeProvider theme={store.theme}>
        

        <Provider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </Provider>
      </ThemeProvider>
    </body>
  </html>
)*/

